### ISSUE TITLE
Unity's buffers

### ISSUE THREAD

**Issue by PeppeDK** [unity3d-jp/RaytracedHardShadow#34]
it would be great if you could pass unity's buffers like: "normal, albedo,..." in the shader "rthsShadowDXR.hlsl"

**Comment by i-saint** [comment]
we have no plan to do it. what is your use case?

**Comment by PeppeDK** [comment]
I would like to calculate specular effect for lights on rths, and to do it i need to get normals.
I'd like to read le normal through unity buffers rather than through the vertices of the 3d model.
If u think its not important, can u anyway just help me to pass textures from unity to rths? and read these on "rthsShadowDXR.hlsl"?.

Thanks, and congratulations for your job.

**Comment by i-saint** [comment]
this plugin's purpose is just rendering hard shadows (mainly on legacy render pipeline). all the others are beyond the scope.
I recommend you to use Unity 2019.3 (beta) + HDRP. it supports raytracing. if you are really willing to fork and modify this plugin, Texture.GetNativeTexturePtr() will be your best friend.
